CREATE DATABASE Employe;
CREATE TABLE Employe_Details(id int,emp_name varchar(20),emp_id int,emp_dept varchar(20),emp_sal int,emp_mng_name varchar(20),mgr_id int,emp_exp varchar(20)) 
SELECT * FROM Employe_Details;
INSERT INTO Employe_Details(id,emp_name,emp_id,emp_dept,emp_sal,emp_mng_name,mgr_id,emp_exp)values(1,"anusha",200,"software engineer",40000,"deepika",300,2);
INSERT INTO Employe_Details(id,emp_name,emp_id,emp_dept,emp_sal,emp_mng_name,mgr_id,emp_exp)values(2,"ramya",201,"software engineer",30000,"poojash",301,1);
INSERT INTO Employe_Details(id,emp_name,emp_id,emp_dept,emp_sal,emp_mng_name,mgr_id,emp_exp)values(3,"rakshitha",202,"software engineer",45000,"neha",302,3);
INSERT INTO Employe_Details(id,emp_name,emp_id,emp_dept,emp_sal,emp_mng_name,mgr_id,emp_exp)values(4,"gagana",203,"software engineer",550000,"kavya",303,3);
INSERT INTO Employe_Details(id,emp_name,emp_id,emp_dept,emp_sal,emp_mng_name,mgr_id,emp_exp)values(5,"sarika",204,"software engineer",80000,"pallavi",304,3);
INSERT INTO Employe_Details(id,emp_name,emp_id,emp_dept,emp_sal,emp_mng_name,mgr_id,emp_exp)values(6,"mani",205,"software engineer",90000,"nethra",305,1);
INSERT INTO Employe_Details(id,emp_name,emp_id,emp_dept,emp_sal,emp_mng_name,mgr_id,emp_exp)values(7,"manjunatha",206,"software engineer",65000,"kishore",306,2);
INSERT INTO Employe_Details(id,emp_name,emp_id,emp_dept,emp_sal,emp_mng_name,mgr_id,emp_exp)values(8,"hemavathi",207,"software engineer",80000,"karna",307,3);
INSERT INTO Employe_Details(id,emp_name,emp_id,emp_dept,emp_sal,emp_mng_name,mgr_id,emp_exp)values(9,"ranganna",208,"software engineer",50000,"kaveri",308,5);
INSERT INTO Employe_Details(id,emp_name,emp_id,emp_dept,emp_sal,emp_mng_name,mgr_id,emp_exp)values(10,"savitha",209,"software engineer",45000,"banashankari",309,6);
INSERT INTO Employe_Details(id,emp_name,emp_id,emp_dept,emp_sal,emp_mng_name,mgr_id,emp_exp)values(11,"nagaveni",210,"software engineer",60000,"vijay",400,4);
INSERT INTO Employe_Details(id,emp_name,emp_id,emp_dept,emp_sal,emp_mng_name,mgr_id,emp_exp)values(12,"shashi",211,"software engineer",70000,"naani",401,3);
INSERT INTO Employe_Details(id,emp_name,emp_id,emp_dept,emp_sal,emp_mng_name,mgr_id,emp_exp)values(13,"raamu",212,"software engineer",90000,"yash",402,2);
INSERT INTO Employe_Details(id,emp_name,emp_id,emp_dept,emp_sal,emp_mng_name,mgr_id,emp_exp)values(14,"raaju",213,"software engineer",140000,"sudeep",403,1);
INSERT INTO Employe_Details(id,emp_name,emp_id,emp_dept,emp_sal,emp_mng_name,mgr_id,emp_exp)values(15,"kiran",214,"software engineer",60000,"saniya",404,3);
INSERT INTO Employe_Details(id,emp_name,emp_id,emp_dept,emp_sal,emp_mng_name,mgr_id,emp_exp)values(16,"shivu",215,"software engineer",70000,"sonu",405,5);
INSERT INTO Employe_Details(id,emp_name,emp_id,emp_dept,emp_sal,emp_mng_name,mgr_id,emp_exp)values(17,"prakruthi",216,"software engineer",75000,"kalyani",406,8);
INSERT INTO Employe_Details(id,emp_name,emp_id,emp_dept,emp_sal,emp_mng_name,mgr_id,emp_exp)values(18,"megha",217,"software engineer",35000,"manoj",407,3);
INSERT INTO Employe_Details(id,emp_name,emp_id,emp_dept,emp_sal,emp_mng_name,mgr_id,emp_exp)values(19,"sangeetha",218,"software engineer",95000,"mariya",408,5);
INSERT INTO Employe_Details(id,emp_name,emp_id,emp_dept,emp_sal,emp_mng_name,mgr_id,emp_exp)values(20,"poojar",219,"software engineer",200000,"boomika",409,8);